[Variables]

;visit www.weather.codes to find a code for your location.
Location=RPXX1258
;en_GB for metric, en_US for imperial. You can add your own language (for example fr_FR for French, or ja_JP for Japanese) but it will break some things
Language=en_GB

; Opacity of the black background, between 0 and 255 (default : 192)
BackgroundOpacity=0

;You can set the color of the accents to be Dynamic (meaning it will use Chameleon to pick a color from your wallpaper) or Static (which will use the color you chose below)
AccentColor=Static
StaticAccentColor=255,255,255

;Change the size of the whole skin. I recommend staying between 0.5 and 1.4.
;Massive thanks to Basketballforce/Screwyoudeviantart12 who did the bulk of the work for this feature !
Scale=0.85

;The time (in minutes) between each update. By default the skin connects to weather.com every minute
UpdateEvery=3

;This setting removes the air quality, UV, Pollen and Dew Point meters to make a more compact top section. 0 = Disabled, 1 = Enabled
;Thanks to aeroplanekelly for suggesting this feature!
CompactCurrentConditions=1

HourlyTimeFormat=12

BackgroundColor=0,0,0
ContentColor=255,255,255
ImgTintColor=255,255,255
AccentGradient=Light2

RoundedCorners=30
