[Variables]

Language=English
Location=SPXX0050
Unit=m
Player=WMP
Format=#I
Hidden=1
Hidden2=0
TextColor=255,255,255
BackgroundColor=187,1,1

;-------------------------------------------------------------
;-------------------------------------------------------------

;DOCK SETTINGS:

;This below is the settings for the dock with icons.
;If you are not familiar with Rainmeter from earlier,please don't edit anything!
;It's too complicated and sensitive,if you don't know what you doing!
;But i will try to explain to you as much as i can.This "#@#\" is shortened for "@Resources" folder.It's a folder where the icons and other parts of the skin are located.
;If you want to change icon-s,new icon-s,you must put in "@Resources" folder.Also,icons must be in PNG file format.
;When you change "icon and name path",for example if you want to change "My Computer" icon to "CCleaner",it should look like this:

;This is example for some program:

;Icon1NameAndPath=#@#\CCleaner.png
;Icon1Text=CCleaner
;LocationPath1=["C:\Program Files\CCleaner\CCleaner64.exe"]

;This is example for some internet links:

;Icon4NameAndPath=#@#\Twitter.png
;Icon4Text=Twitter
;LocationPath4=["https://twitter.com/?lang=en"]

;etc..

;On this site : https://docs.rainmeter.net/manual/getting-started/customizing/
;you can find all information,about customizing some skin.To change color,font,size,etc..
;You can also learn how to make your first skin. :)
;Thank you for your understanding! :)


;----------------------Internet Links Settings-------------------
;----------------------------------------------------------------


LinkIcon1NameAndPath=#@#\Google.png
Link1Text=Google
LinkLocationPath1=["https://google.com"]

LinkIcon2NameAndPath=#@#\Facebook.png
Link2Text=Facebook
LinkLocationPath2=["https://facebook.com/"]

LinkIcon3NameAndPath=#@#\Gmail.png
Link3Text=Gmail
LinkLocationPath3=["https://mail.google.com/mail/"]

LinkIcon4NameAndPath=#@#\Deviantart.png
Link4Text=Deviantart
LinkLocationPath4=["https://www.deviantart.com/browse/all/customization/skins/sysmonitor/rainmeter/?order=5"]

LinkIcon5NameAndPath=#@#\Twitter.png
Link5Text=Twitter
LinkLocationPath5=["https://twitter.com/"]

LinkIcon6NameAndPath=#@#\Unsplash.png
Link6Text=Unsplash
LinkLocationPath6=["https://unsplash.com/"]
